productos = [
    {
        "id": 160,
        "nombre": "Celular",
        "descripcion": "Samsung S25+",
        "precio": "$7,345,999",
        "rating": 4.5,
    }, {
        "id": 175,
        "nombre": "Tablet",
        "descripcion": "Acer Tablematic",
        "precio": "$1,100,000",
        "rating": 2,
    }, {
        "id": 8,
        "nombre": "Notebook",
        "descripcion": "Lenovo Yoga Master",
        "precio": "$4,900,500",
        "rating": 3.5,
    }, {
        "id": 96,
        "nombre": "Console",
        "descripcion": "Sony PlayStation 6X",
        "precio": "$2,159,999",
        "rating": 2.5,
    },
    {
        "id": 201,
        "nombre": "Smartwatch",
        "descripcion": "Apple Watch Series 10",
        "precio": "$1,789,000",
        "rating": 4.7,
    },
    {
        "id": 145,
        "nombre": "Auriculares",
        "descripcion": "Sony WH-2000XM5",
        "precio": "$899,990",
        "rating": 4.8,
    },
    {
        "id": 67,
        "nombre": "Monitor",
        "descripcion": "LG UltraWide 38''",
        "precio": "$2,450,000",
        "rating": 4.3,
    },
    {
        "id": 211,
        "nombre": "Cámara",
        "descripcion": "Canon EOS R8",
        "precio": "$3,250,000",
        "rating": 4.6,
    },
    {
        "id": 45,
        "nombre": "Altavoz",
        "descripcion": "Bose SoundLink Revolve II",
        "precio": "$599,900",
        "rating": 3.9,
    },
    {
        "id": 124,
        "nombre": "Impresora",
        "descripcion": "Epson EcoTank L8950",
        "precio": "$1,250,000",
        "rating": 3.8,
    },
    {
        "id": 190,
        "nombre": "Router",
        "descripcion": "TP-Link Archer AX95",
        "precio": "$455,000",
        "rating": 4.1,
    },
    {
        "id": 78,
        "nombre": "Teclado",
        "descripcion": "Logitech MX Keys S",
        "precio": "$349,990",
        "rating": 4.4,
    },
    {
        "id": 156,
        "nombre": "Mouse",
        "descripcion": "Razer DeathAdder V3",
        "precio": "$199,990",
        "rating": 4.5,
    },
    {
        "id": 223,
        "nombre": "Disco SSD",
        "descripcion": "Samsung 990 PRO 2TB",
        "precio": "$520,000",
        "rating": 4.9,
    },
    {
        "id": 89,
        "nombre": "Proyector",
        "descripcion": "Epson PowerLite 5050UB",
        "precio": "$3,890,000",
        "rating": 4.2,
    },
    {
        "id": 177,
        "nombre": "Drone",
        "descripcion": "DJI Mavic 4 Pro",
        "precio": "$3,999,900",
        "rating": 4.7,
    },
    {
        "id": 33,
        "nombre": "TV",
        "descripcion": "Samsung Neo QLED 8K 85''",
        "precio": "$12,500,000",
        "rating": 4.8,
    },
    {
        "id": 249,
        "nombre": "Powerbank",
        "descripcion": "Anker PowerCore 26800",
        "precio": "$189,900",
        "rating": 4.3,
    },
    {
        "id": 112,
        "nombre": "Webcam",
        "descripcion": "Logitech StreamCam Pro",
        "precio": "$420,000",
        "rating": 3.7,
    },
    {
        "id": 187,
        "nombre": "Consola Portátil",
        "descripcion": "Nintendo Switch 2",
        "precio": "$1,850,000",
        "rating": 4.6,
    },
    {
        "id": 56,
        "nombre": "Reproductor",
        "descripcion": "Roku Ultra 4K HDR",
        "precio": "$349,990",
        "rating": 4.0,
    },
    {
        "id": 231,
        "nombre": "Kindle",
        "descripcion": "Amazon Kindle Oasis 2025",
        "precio": "$480,000",
        "rating": 4.4,
    },
    {
        "id": 142,
        "nombre": "Tarjeta Gráfica",
        "descripcion": "NVIDIA RTX 5090 Ti",
        "precio": "$5,499,900",
        "rating": 4.9,
    },
    {
        "id": 76,
        "nombre": "Procesador",
        "descripcion": "AMD Ryzen 9 9950X",
        "precio": "$2,300,000",
        "rating": 4.7,
    },
]
